before_script:
  - sed -i.bak 's/dl-cdn.alpinelinux.org/mirrors.edge.kernel.org/g' /etc/apk/repositories
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml awscli
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - aws s3 cp s3://fh-app-support/lzhao/hai/preddata_2022_05_18_full.Rdata ./data/
    - docker build -t sc-registry.fredhutch.org/hai:test .
    - rm data/preddata_2022_05_18_full.Rdata
    - docker push sc-registry.fredhutch.org/hai:test


test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/hai:test
      alias: hai
  script:
    - sleep 300 && curl -sI  http://hai:3838  |head -1|grep -q "200 OK"
  
  
deploy:
  stage: deploy
  only:
    refs:
       - main
  script:
    - docker tag sc-registry.fredhutch.org/hai:test sc-registry.fredhutch.org/hai:latest
    - docker push sc-registry.fredhutch.org/hai:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - hai
    
